### ISSUE TITLE
Issue using paramsurvey on my machine (python 3.11)

### ISSUE THREAD

**Issue by ptiede** [wumpus/paramsurvey#5]
I am having an issue installing paramsurvey on my machine. I am guessing this has to do with the fact that I just had to update my system to python 3.11. When I try to pip install paramsurvey I get the following error:

```
> pip install --user paramsurvey
Collecting paramsurvey
  Using cached paramsurvey-0.4.18.tar.gz (159 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      /usr/lib/python3.11/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error in paramsurvey setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.7.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```

This suggests the fix `pip install --use-pep517` but that still fails on my machine with the error
```
> pip install --use-pep517 --user paramsurvey
Collecting paramsurvey
  Using cached paramsurvey-0.4.18.tar.gz (159 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in paramsurvey setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.7.*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

```
Python 3.11.3
```

```
OS: EndeavourOS 
Kernel: Linux 6.3.2-arch1-1
```
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  32
  On-line CPU(s) list:   0-31
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 9 7950X 16-Core Processor
```

**Comment by wumpus** [comment]
Paul,

There's some chaos in the python world these days, but here's a recipe for installing under python 3.11:

- one problem is that you have to update setuptools... the one shipped with 3.11 is not recent enough (!?!)
- one problem is that my packaging for paramsurvey and pandas-appender uses a requires string like 3.7.* and that is now illegal.

So to dodge these 2 problems:

- `pip install -U setuptools`
- `git clone git@github.com:wumpus/pandas-appender.git pandas-appender-paul`
- cd to this directory, edit setup.py to make this change:
> `-    python_requires=">=3.6.*",`
> `+    python_requires=">=3.6",`
- `pip install .`
- `cd ..`
- `git clone git@github.com:wumpus/paramsurvey.git paramsurvey-paul`
- cd to this directory, edit setup.py to make this change:
> `-    python_requires=">=3.7.*",`
> `+    python_requires=">=3.7",`
- `pip install .`

I would release new packages to fix this, but, `setuptools-scm` has been broken for a while and that causes me problems. Maybe that's fixed, I'll look again.

**Comment by wumpus** [comment]
Oh, man, the pandas guys removed DataFrame.append() after all  &$*#&^*^$*#$^&

**Comment by wumpus** [comment]
Paul, I have pushed new versions of pandas-appender and paramsurvey to pypi which ought to fix this problem.

There is a (new) limitation of numpy<2, however.

**Comment by wumpus** [comment]
Paul, the latest release should keep you happy.
